### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by simonegenovese** [grover/homebridge-telegram#1]
Dear grover,
I've installed the telegram module and configured and I get this logs:
```
[2017-12-3 14:59:11] Loading 1 platforms...
[2017-12-3 14:59:11] [Telegram] Initializing Telegram platform...
[2017-12-3 14:59:11] [Telegram] TelegramPlatform Plugin Loaded
[2017-12-3 14:59:11] [Telegram] Found bot in config: "BB8"
[2017-12-3 14:59:11] [Telegram] Initializing platform accessory 'BB8'...
[2017-12-3 14:59:11] [Roomba] Initializing Custom-Http accessory...
Load homebridge-telegram.Telegram
[2017-12-3 14:59:11] [homebridge-telegram.Telegram] TelegramPlatform Plugin Loaded
.....

                       
[2017-12-3 14:59:11] Homebridge is running on port 51826.
I am @bb8_case_bot, right? :)
```
and I suppose everything is working correctly.
But when I add the device to my HomeKit then I can't see the Telegram platform,
how is supposed to be used?
Thanks.

**Comment by grover** [comment]
Hi,

which app are you using? From the excerpt of the logs everything seems to work as expected.

Thanks!

**Comment by simonegenovese** [comment]
Dear Grover,
I’m using standard homekit by apple. When adding the device I can see all the other devices managed by homebridge except telegram. 
After some time i’ve Received a message by the bot and in the err log file I've discovered this exception:
'''Failed to get updates.Error: connect EINVAL 149.154.167.198:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
The bot has failed fatally. Will not send any further messages or attempt to talk to Telegram.'''

**Comment by grover** [comment]
That looks like a configuration problem. Did you configure the bot token properly? (Don't post it here, please.)

Also you can't use the same bot multiple times from different homebridge installations. That failed message indicates that you either have the wrong bot token or something else has been trying to get updates for the bot.

Finally, while the telegram accessory device does show up in HomeKit you can't configure or really use it there. I'd recommend using the Elgato Eve app.

Please also try updating to 0.0.5 if you're not already using it.

**Comment by simonegenovese** [comment]
Ok, it worked.
The problem was that I was using the same telegram token and bot through
another service.
I can see te bot on Eve and use it.
Thanks



On 4 dicembre 2017 a 01:22:41, Michael Fröhlich (notifications@github.com)
scritto:

That looks like a configuration problem. Did you configure the bot token
properly? (Don't post it here, please.)

Also you can't use the same bot multiple times from different homebridge
installations. That failed message indicates that you either have the wrong
bot token or something else has been trying to get updates for the bot.

Finally, while the telegram accessory device does show up in HomeKit you
can't configure or really use it there. I'd recommend using the Elgato Eve
app.

Please also try updating to 0.0.5 if you're not already using it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/grover/homebridge-telegram/issues/1#issuecomment-348832931>,
or mute the thread

**Comment by grover** [comment]
FYI the update I published yesterday should enable reconnects if you use the same bit multiple times. It won’t fix the underlying issue in the telegram APIs, but it’s a start.
