### ISSUE TITLE
„Something broken. I'm shutting down.“

### ISSUE THREAD

**Issue by AlfaJackal** [grover/homebridge-telegram#14]
Please excuse I am asking such a trivial question! Is possible to use homebridge-telegram and another telegram service like in home assistant at the same time?

I am running Homebridge-telegram successfully for about one year. Now I tried home assistant and configured the same `api_key` and `chat_id`. And then suddenly, Homebridge-telegram has been sending me error messages with „Something broken. I'm shutting down.“

How can I fix that and use both services with the same bot and chat?

**Comment by roboterm** [comment]
Had the same issue when trying to use my already in use Telegram bot for a Dafang service. 
Ended up in creating another bot for the new service. 
Dunno if this is the best practice...
