### ISSUE TITLE
Not working in iOS 14 (dev beta 4)

### ISSUE THREAD

**Issue by vidalpascual** [grover/homebridge-telegram#15]
The plugin is not working any more in iOS 14. Is not possible (in the Eve app) to activate the switch of the notification any more: _"HomeKit reports that the accessory is not accessible"_

![Captura 2020-08-13 a las 8 30 59](https://user-images.githubusercontent.com/3727107/90101804-a50d1e80-dd3f-11ea-893e-baef8d3ce35b.png)

**Comment by roboterm** [comment]
Can not confirm this. Everything is working fine on my iPhone running iOS 14 PB 4. 
My HK hub (ATV4) is also running the tvOS 14 Beta.  
![A0265525-7FA6-43E4-AE86-6A5252001189](https://user-images.githubusercontent.com/5045476/90110427-7eee7b00-dd4d-11ea-92d3-1860966e2382.png)

**Comment by grover** [comment]
Do not ask me about prerelease Apple software. They’re known broken and I would not use them at home. I’ll try to take some time in the fall when they’re ready.
