### ISSUE TITLE
No message appears in bot after a trigger

### ISSUE THREAD

**Issue by Domot** [grover/homebridge-telegram#2]
Hello Grover,
My compliments for the nice feature you have created for use with HomeKit!
I have an issue regarding the incoming messages in the bot. No errors during the initializing of config.json, it shows the username of the created Telegram Bot, by triggering the button the Homebridge log shows that the message is sent, but it does not show up as a message in my private Telegram account. Quiet parameter is False and Message nummer is in the range of the created two messages in the config.json script. When I sent a message to the created Telegram Bot I do receive the details of the message in the Homebridge log so there is an active connection. Do you have any suggestions what I am doing wrong?

**Comment by grover** [comment]
My best guess is that you used the wrong cat id. That should be the chat id of the destination, where the bot will send messages to.

Another reason might be that you haven’t invited the bot to the chat yet. As far as I know bots can’t initiate a conversation, but must be invited there.

**Comment by Domot** [comment]
Hello Grover,
You are right. I did use my alias name as chat id instead of the 8 digit code. May something to make more clear in your documentation.
I works like a charm now.
